version: 0.2
phases:
#   pre_build:
#     commands:
#       - echo Installing source NPM dependencies...
#       - npm install
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --s3-bucket b1-front-end-photosearch
artifacts:
  files:
    - '**/*'
  base-directory: build
